services:
  # Frontend Web Service
  - type: web
    name: speakeasy-client
    env: node
    plan: free
    buildCommand: cd client && npm install && npx cross-env GENERATE_SOURCEMAP=false npx react-app-rewired build
    startCommand: cd client && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_GIPHY_API_KEY
        sync: false
      - key: PORT
        value: 3000
    autoDeploy: true
    domains:
      - speakeasy-client.onrender.com
    runtime: node
    nodeVersion: 18.x

  # Backend API Service
  - type: web
    name: speakeasy-server
    env: node
    plan: free
    buildCommand: cd server && npm install && mkdir -p dist && cp -r src/* dist/
    startCommand: cd server && node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GIPHY_API_KEY
        sync: false
      - key: CLIENT_URL
        value: https://speakeasy-client.onrender.com
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: "false"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
    autoDeploy: true
    runtime: node
    nodeVersion: 18.x