services:
  # Frontend Web Service
  - type: web
    name: speakeasy-client
    env: node
    rootDir: client
    plan: free # Adjust as needed
    buildCommand: npm install && npm run build
    startCommand: npm run serve
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_GIPHY_API_KEY
        sync: false # Add this manually in Render dashboard
      - key: PORT
        value: 3000
    healthCheckPath: /
    autoDeploy: true
    domains:
      - speakeasy-chat.onrender.com # Replace with your desired domain
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 