services:
  - type: web
    name: chat-client
    env: node
    buildCommand: cd client && npm install --include=dev && npm run lint:fix || true && npm run build
    startCommand: cd client && npm install -g serve && serve -s build -l $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        fromService:
          name: chat-server
          type: web
          property: hostport
      - key: REACT_APP_SOCKET_URL
        fromService:
          name: chat-server
          type: web
          property: host
      - key: REACT_APP_NAME
        value: Signal Chat
      - key: REACT_APP_DESCRIPTION
        value: Secure messaging app with Signal Protocol end-to-end encryption
      - key: REACT_APP_VERSION
        value: 1.0.0
    autoDeploy: true

  - type: web
    name: chat-server
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: CLIENT_URL
        fromService:
          name: chat-client
          type: web
          property: host
      - key: CORS_ORIGIN
        fromService:
          name: chat-client
          type: web
          property: host
      - key: PORT
        value: 10000
    autoDeploy: true
    healthCheckPath: /api/health 