services:
  # Frontend Web Service
  - type: web
    name: speakeasy-client
    env: node
    plan: free # Adjust as needed
    buildCommand: cd client && npm install && npx react-app-rewired build
    startCommand: cd client && npm run serve
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_GIPHY_API_KEY
        sync: false # Add this manually in Render dashboard
      - key: PORT
        value: 3000
    healthCheckPath: /
    autoDeploy: true
    domains:
      - speakeasy-chat.onrender.com # Replace with your desired domain