services:
  # Frontend Web Service
  - type: web
    name: speakeasy-client
    env: node
    plan: free
    buildCommand: cd client && npm install && npx cross-env GENERATE_SOURCEMAP=false npx react-app-rewired build
    startCommand: cd client && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_GIPHY_API_KEY
        sync: false
      - key: PORT
        value: 3000
    healthCheckPath: /
    autoDeploy: true
    domains:
      - speakeasy-chat.onrender.com # Replace with your desired domain