services:
  - type: web
    name: speakeasy-client
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm run serve
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_GIPHY_API_KEY
        sync: false
    autoDeploy: true
    healthCheckPath: /
    disk:
      name: speakeasy-uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1 